### ISSUE TITLE
Mouseover Crash

### ISSUE THREAD

**Issue by TheBambino** [direwolf420/PetRenamer#3]
Crashes game client when mouseovering a renamed pet in multiplayer. Not 100%, can't reproduce on demand, but it occasionally happens. 

[client (16).log](https://github.com/direwolf420/PetRenamer/files/6953228/client.16.log)

**Comment by direwolf420** [comment]
I can only attempt to fix it but it's not a guarantee, let me know if it breaks again after the 1.1.2.1 update
